language: ruby
rvm:
- 2.2.2
script: ./cibuild.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
git:
  depth: 10
before_deploy: pip install --user s3cmd
deploy:
- provider: script
  skip_cleanup: true
  script: ./s3_push.sh -b s3://dev-door43.org
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: ./s3_push.sh -b s3://door43.org
  on:
    branch: master
