# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Door43
email: help@door43.org
description: unrestricted biblical content in every language
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://door43.org"

# Build settings
exclude: [assets, assets_sync.sh, Gemfile*, README.md, LICENSE, s3*, secrets*, vender, cibuild.sh, Makefile, karma*,
          run_karma_tests.sh, node_modules/*, package-lock.json, package.json, temp-data.json, coverage, test/*]

gems:
  - jekyll-sitemap

markdown: kramdown

sass:
  style: compact
